### ISSUE TITLE
Testing Project

### ISSUE THREAD

**Issue by NLSuarez** [Ssuarez0/CS4300-Group-Projects#1]
I will begin testing from a .txt file I create tomorrow. I will also post the .txt file I make to this repository in case anyone wants to also test.

**Comment by NLSuarez** [comment]
Git has been cloned and my testing environment is set up. I will be constructing the test data now. I'm assuming the list will be around 25-50 numbers separated by enter, but I will focus mainly on every single pattern I can imagine.

**Comment by NLSuarez** [comment]
I'm not yet done creating my file, but I have noticed a bug already.
80-90 is an input that gets split into two numbers, which it should not be by the rules of the project. Make sure that the code accounts for spacing issues like in Thursday's class example.

Note: I won't put in tabs to the test data, as per the instructions; but we should be prepared for spaces and newlines.

**Comment by NLSuarez** [comment]
test-data.txt is done and uploaded, at least for now. I tried to input a variety of strings to test the pattern recognizer, so it may make the program need more patterns. There's an error with recognizing whole numbers, as stated above, so make sure to account for that. The stats you should get for this file are 35 possible numbers and 17 numbers. Any more or less is incorrect. Also, the file is in Manjinder's primary folder if anyone is looking for it.

**Comment by tferguson7337** [comment]
I'm counting 36 possibles, with my version matching 16 of them as numbers.  Could you include a key to go along with the input file, just so we can double check?  I'll upload my program's output in a sec.

**Comment by NLSuarez** [comment]
Sure. I need a few minutes to type it in.

Edit: oh, I see why you got 36. Yes, there are 36. I miscounted there.
Edit 2: Your numbers are correct. I miscounted twice, and this is why we use computers. P:
Key will be uploaded momentarily.

**Comment by HavikIV** [comment]
I've updated my pattern for catching nonnumbers, but personally I do like Tom's smaller and cleaner pattern.

**Comment by tferguson7337** [comment]
Excellent, thank you Manjinder!

**Comment by HavikIV** [comment]
Tom what does \v, \f, \r match?

**Comment by tferguson7337** [comment]
Various things that are considered white space.

\v matches the vertical tab, \f matches form feed (basically a page break that signals a printer to eject the current page and continue on the next), and \r matches carriage return.

**Comment by HavikIV** [comment]
oh, thanks for clearing that. As these weren't on the Flex Manual Page, I had no idea what they did.

**Comment by NLSuarez** [comment]
I will continue testing until I'm satisfied it won't break, but are we set on using Thomas' code for the cleaner patterns?

**Comment by tferguson7337** [comment]
Sounds good to me.

Edit:
I should note that my pattern for floating point numbers does match -0.000... and 0.000....  This doesn't seem to be in conflict with the specifications (to my knowledge, anyway), but if it turns out to be it's a very easy fix.

**Comment by HavikIV** [comment]
Yea sure. Personally I do feel that we can combine the first three patterns into one like the following: {Integers}{Float}?{Exp}?, as Float builds from integers and exponents from builds from the previous two, but it comes down to personal tastes.

**Comment by NLSuarez** [comment]
I've tested both now and they both work despite my shenanigans. If we turn in Thomas', we should make sure that the printed messages say "number" and "not number" per the instructions. Honestly, though, I would just comment out the current pattern messages instead of deleting them cause those are better for debug purposes at a later time.

As for that pattern, we could probably make it work but it would also make the pattern messier. In this case, I say we opt for cleanliness of the patterns so that they're easy to understand and well separated.

**Comment by tferguson7337** [comment]
Agreed.  The output my code has was only ever intended for debugging purposes anyway.

**Comment by HavikIV** [comment]
Hey Thomas, wouldn't it be simpler to use the following as the pattern for hexadecimal numbers?
[-]?(0[xX][0-9A-F]+)
instead of:
-?0[xX] (0|([1-9A-F][0-9A-F]*))

**Comment by tferguson7337** [comment]
If I'm not mistaken, no.  A quick test showed that [-]?(0[xX][0-9A-F]+) will match hexadecimal numbers with leading zeroes, which isn't allowed (e.g., 0x00000 or 0x0A)  
The only time a leading zero is allowed is when there is only one zero to the right of the x (i.e., 0x0).

**Comment by HavikIV** [comment]
Ah, I forgot about about the leading 0's

**Comment by NLSuarez** [comment]
Just keeping everyone updated that I have been expanding the test-data this weekend. I should have a completely uploaded version within the next two hours. I've been going through every possible configuration and am already over 50 numbers now, which is what I wanted.

**Comment by NLSuarez** [comment]
Test data uploaded. I've been having some crashing issues with my virtual box this morning so I was slowed down slightly. The total "possible numbers" is now up to 87. Manjinder's code misses the leading zeroes for hex, but I couldn't break Thomas' in the same way so we're good to go with his except for comments denoting who did what.

**Comment by NLSuarez** [comment]
Header added into Thomas' .l file now as well. I'll turn both the test data and Thomas' .l file into the cs system on Monday in the evening. Look over everything before then to make sure we aren't missing anything that I didn't catch.

**Comment by tferguson7337** [comment]
I renamed the appropriate files in my directory to match what Dr. Carter wants when we submit it (the flex program file should be named numbers.l and the input file should be named test-data.txt).  I also changed the makefile to account for the file name change and added a bit to the makefile to name the executable proj1.  The makefile doesn't really matter though, since we're just going to end up uploading the program and the data.

Aside from that, I think we're ready to submit.

**Comment by NLSuarez** [comment]
I'm pulling down the files now to submit.

**Comment by NLSuarez** [comment]
Fixed an error in your makefile, Thomas, since it still referenced the old file name in the header.

Both files are uploaded now, significantly past when I was hoping because of an extreme crisis on my virtual box that has now destroyed it and forced me to recreate it on the weekend. Word to the wise: avoid tar files except as a final resort. You may develop PTSD like me and start shouting Satan every time you see the extension.
